### ISSUE TITLE
Support protocol version R38

### ISSUE THREAD

**Issue by ste93cry** [RConDev/rcondevserver#14]
Hi,
currently the program doesn't support the R38 version of the server protocol and there is no way to handle the recent changes of the RCON. Could the support be added?

**Comment by m4cx** [comment]
I'm sorry that I haven't provided it yet, but I haven't found the documentations yet. 
If you can provide me them, I will have a look into it and will add the support.

**Comment by ste93cry** [comment]
I can't understand if the R38 version really exists or if we're at R34. Officially I can't find the version for which I asked to implement the support but on another [GitHub repository](https://github.com/RConDev/RaptoRCon/raw/development/doc/games/bf3/Battlefield3_AdminDocs_R38.zip) I found the PDFs of the docs. There is a bit of confusion in the PDFs I found: the only reference to this version is in the file named BF3 PC Server Remote Administration Protocol.pdf. However, it seems that R38 is officially called R34. I don't know what to think but the correct version to implement should be the second

**Comment by m4cx** [comment]
Okay.. The Project you found is also mine. The docs I found yesterday and added them to the r34 docs. I am currently also working on a RCon-Administration tool. 

I will add the support about in one or two  weeks. Is this ok for you?!

**Comment by ste93cry** [comment]
yes it's ok because at the moment I have a real server where to test my RCON-Admin tool, so there is no urgent necessity

P.S. I don't know if you remember me but I'm the one that contacted you a year ago because I was testing my RCON program and I was actively following your DevServerTool. Now that the school is finished I'm back working on it

**Comment by m4cx** [comment]
I can hardly remember. But if you want to participate in the project you mentioned above, feel warmly welcomed.
